### ISSUE TITLE
Not clear instructions in ReadMe

### ISSUE THREAD

**Issue by satish2** [SoftwareEngineeringToolDemos/FSE-2012-REPERTOIRE#3]
ReadMe does not provide instructions on how to start GUI is the user closes the one that starts up with Operating System. Better, if steps in "REPERTOIRE Instructions.txt" are copied to ReadMe.txt file. 

Also, step that explains how to select ccFinder path, does not mention the path where user can find <i>RepertoireTool-master</i> directory.

**Comment by skollip** [comment]
Merged instructions for REPERTOIRE into readme and provided clearer details on ccFinder path

Closed #3
